name: Build Packages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Build Packages
        run: ./build.sh
      - name: GitHub Pages
        run: |
          mkdir -p public
          find packages -name "*.pkg.tar.zst" -exec cp {} public/ \;
          repo-add public/custom.db.tar.gz public/*.pkg.tar.zst
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
