name: Build Packages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set Nopasswd Sudo
        run: echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      - name: Install Packages
        run: pacman -Syyu --noconfirm sudo
      - name: Create builder user
        run: |
          sudo useradd -m builder
          sudo chown -R builder:builder $GITHUB_WORKSPACE
      - name: Build Packages
        run: su builder -c ./build.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
