name: Build Packages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set Nopasswd Sudo
        run: echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      - name: Install Packages
        run: pacman -Syyu --noconfirm sudo gnupg
      - name: Create builder user
        run: |
          sudo useradd -m builder
          sudo chown -R builder:builder $GITHUB_WORKSPACE
      - name: Build Packages
        run: |
          su builder -c "./build.sh clean"
          su builder -c "./build.sh build"
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SECRET_KEY }}" | gpg --batch --import
      - name: Sign Packages
        run: |
          for file in dist/*.pkg.tar.zst; do
            echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --detach-sign --pinentry-mode loopback --passphrase-fd 0 "$file"
          done
      - name: Create Repo
        run: |
          echo "リポジトリを作成しています"
          repo-add dist/tsuki.db.tar.gz --sign dist/*.pkg.tar.zst || { echo "リポジトリ作成に失敗しました"; exit 1; }
      - name: Upload static files
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: dist/
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
